name: Takumi Guard Install Check

on:
  pull_request:
    paths:
      - .github/workflows/takumi-guard-install-check.yml

permissions:
  id-token: write
  contents: read

jobs:
  install-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '24'
          cache: npm

      - uses: flatt-security/setup-takumi-guard-npm@6d4182745c1e474c35a023573c2612c085be45a4 # v1.2.0
        with:
          bot-id: BT01M1X4E4R7QZY0RMYG8HSXQQXA

      - run: npm ci
